### ISSUE TITLE
Add a note about v0.3 compatibility

### ISSUE THREAD

**Issue by matthewware** [BBN-Q/QSimulator.jl#5]
Seems like master isn't compatible with versions below 0.4 after switching to the new Tuples.  Should we add a note in the doc about that?

**Comment by caryan** [comment]
I made a cursory attempt to use some Compat.jl macros as it supports the tuple changes but it didn't seem to work with the arrays of tuples we have.  Julia 0.4 should be pretty close now (10 days overdue) so we'll just make it a requirement.
